### PR TITLE
Upgrade to commerce v14

### PR DESCRIPTION
**Pull request by umbracotrd**
The setting page for payment provider works fine with `Umbraco Commerce v14-alpha3`.
image

### CODE REVIEW

**Comment by mattbrailsford** [comment]
The only other thing I'm not too keen on (though this is nothing to do with what you've implemented) is the localization keys being a mix of kebab and camel case. We need to keep the payment provider aliases kebab case to maintain backwards compatibility, but I'm going to make an update in the core UC to automatically covert these to camel case when used in these types of keys, this way the localization files are consistent.

I'll be pushing a preview build to the nightly server shortly so you can update your localization file and test this.

**Comment by umbracotrd** [comment]
Thanks, @mattbrailsford, I've removed the `Client`  folder and moved the localization extension to `umbraco-package.json` file

**Comment by mattbrailsford** [comment]
@umbracotrd this looks so much cleaner now 👍

All looking good, but if you want to upgrade to the `alpha3` I just pushed out this morning, this should have the fix in regarding the payment provider label key aliases converting from kebab-case to camelCase so all the keys inside the localization file can have the payment provider aliases be camel case for better consistency. 

Oh, and maybe we can delete the `package.lock.json` file now too.

After than, I think it looks good.

**Review by mattbrailsford — APPROVED** [review]

**Comment by umbracotrd** [comment]
Tested OK with umbraco commerce 14-beta2

**Comment by umbracotrd** [comment]
Tested with checkout 14alpha2 and commerce rc2

**Pull request merged**
